[package]
name = "finacolada"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "0.11", features = ["json"]}
tokio = {version = "1", features = ["macros", "rt-multi-thread"]}

[dev-dependencies]
chrono = "0.4.23"
insta = { version = "1.26.0", features = ["yaml"] }

